name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - pip
  - pip:
    - pandas==2.2.2
    - numpy==1.26.4
    - seaborn==0.13.2
    - matplotlib==3.8.4
    - torch==2.3.0
    - pillow==10.3.0
    - opencv-python==4.9.0.80
    - torchvision==0.18.0
    - tqdm==4.66.2
    - scikit-learn==1.4.2
    - mlflow==2.12.1
    - azureml-mlflow==1.56.0